name: Cache quickget_ci

on:
  repository_dispatch:
    types: [ push-event ]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'lj3954/quickemu-rs'
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --verbose --bin quickget_ci --release

      - name: Cache
        uses: actions/cache@v4
        with:
          path: target/release/quickget_ci
          key: ${{ runner.os }}-quickget_ci-${{ hashFiles('**/Cargo.lock') }}

      - name: Start config generation
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          event-type: generate_configuration
