name: Cache quickget_ci

on:
  push:
    branches:
      - master

jobs:
  cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --verbose --bin quickget_ci --release

      - name: Cache
        uses: actions/cache@v4
        with:
          path: target/release/quickget_ci
          key: ${{ runner.os }}-quickget_ci-${{ hashFiles('**/main.rs') }}

      - name: Start config generation
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: generate_configuration
