name: Create quickget configs

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [ generate_configuration ]

jobs:
  create_configs:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'lj3954/quickemu-rs'
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: target/release/quickget_ci
          key: ${{ runner.os }}-quickget_ci-${{ hashFiles('**/Cargo.lock') }}

      - name: Create configs
        run: ./target/release/quickget_ci

      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'quickget_data.json, quickget_data.json.zst, quickget_data.json.gz'
          artifactContentType: 'application/octet-stream'
          body: 'Quickget configuration files'
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Quickget configurations"
          tag: 'daily'
